#!/usr/bin/env python
# Build script for the TaikoMove hardware GDExtension (PS Move + PS3 Eye).
#   scons platform=windows target=template_release use_mingw=yes   (cross-compile on Linux)
#   scons platform=linux   target=template_release
import os

env = SConscript("godot-cpp/SConstruct")
env = env.Clone()

env.Append(CPPPATH=["src/", "thirdparty/hidapi", "thirdparty/ps3eye", "thirdparty/libusb/include"])
sources = Glob("src/*.cpp") + ["thirdparty/ps3eye/ps3eye.cpp"]

if env["platform"] == "windows":
    sources += ["thirdparty/hidapi/windows/hid.c"]
    env.Append(CPPDEFINES=["TAIKO_WINDOWS", "WIN32_LEAN_AND_MEAN", "NOMINMAX", ("_WIN32_WINNT", "0x0601")])
    env.Append(LIBPATH=[Dir("thirdparty/libusb/mingw64").abspath])
    env.Append(LIBS=["libusb-1.0", "hid", "setupapi", "bthprops", "advapi32", "ws2_32", "ole32"])
    if env.get("use_mingw", False):
        env.Append(LINKFLAGS=["-static-libgcc", "-static-libstdc++", "-static"])
        env.Append(LIBS=["winpthread"])
elif env["platform"] == "linux":
    sources += ["thirdparty/hidapi/linux/hid.c"]
    env.Append(CPPDEFINES=["TAIKO_LINUX"])
    env.Append(CPPPATH=["/usr/include/libusb-1.0"])
    env.Append(LIBS=["usb-1.0", "udev", "pthread"])
else:
    print("Unsupported platform for TaikoMove hardware extension: " + env["platform"])
    Exit(1)

env.Append(CXXFLAGS=["-O2"] if env["target"] == "template_release" else [])

libname = "libtaiko_hw{}{}".format(env["suffix"], env["SHLIBSUFFIX"])
library = env.SharedLibrary("../addons/taiko_hw/bin/" + libname, source=sources)
Default(library)
